<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>zSubscription.Services.KhoiNBD</AssemblyName>
		<RootNamespace>zSubscription.Services.KhoiNBD</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\zSubscription.Repositories.KhoiNBD\zSubscription.Repositories.KhoiNBD.csproj" />
	</ItemGroup>
</Project>