// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zSubscription.Entities.QuangTT.Models;

public partial class FeePackageQuangTt
{
    public int FeePackageQuangTtid { get; set; }

    public string PackageName { get; set; }

    public string Description { get; set; }

    public int? DurationInDays { get; set; }

    public decimal? Price { get; set; }

    public int? Status { get; set; }

    public DateTime? PublishDate { get; set; }

    public virtual ICollection<MembershipFeeQuangTt> MembershipFeeQuangTts { get; set; } = new List<MembershipFeeQuangTt>();
}