// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zSubscription.Entities.KhoiNBD.Models;

public partial class FeePackageKhoiNbd
{
    public int FeePackageKhoiNbdid { get; set; }

    public string PackageName { get; set; }

    public string Description { get; set; }

    public int? DurationInDays { get; set; }

    public decimal? Price { get; set; }

    public int? Status { get; set; }

    public DateTime? PublishDate { get; set; }

    public virtual ICollection<MembershipFeeKhoiNbd> MembershipFeeKhoiNbds { get; set; } = new List<MembershipFeeKhoiNbd>();
}